/* $Id$ */
#include "nsISupports.idl"

[scriptable, uuid(cf89b480-bce3-11de-a0dd-028037ec0200)]
interface rdIMatchResult : nsISupports {
	
	/* Attributes */
	readonly attribute wstring redirectTo;	
	readonly attribute boolean isMatch;
	readonly attribute boolean isExcludeMatch;
	readonly attribute boolean isDisabledMatch;
};

