/* $Id$ */
#include "nsISupports.idl"
#include "rdIMatchResult.idl"

[scriptable, uuid(cb69ddf0-bce1-11de-8251-028037ec0200)]
interface rdIRedirect : nsISupports {
	
	/* Attributes */
	attribute wstring exampleUrl;	
	attribute wstring includePattern;
	attribute wstring excludePattern;
	attribute wstring redirectTo;
	attribute wchar patternType;
	attribute boolean unescapeMatches;
	attribute boolean disabled;
	
	/* Methods */
	rdIRedirect clone();
	void compile();
	void copyValues(in rdIRedirect other);
	void deserialize(in wstring data);
	boolean equals(in rdIRedirect other);
	rdIMatchResult getMatch(in wstring url); 
	boolean isRegex();
	boolean isWildcard();
	wstring serialize();
	rdIMatchResult test(in wstring url); 
};

