/* $Id */
#include "nsISupports.idl"
#include "nsIFile.idl"
#include "rdIRedirect.idl"

[scriptable, uuid(cdf25d91-bce1-11de-aee1-028037ec0200)]
interface rdIRedirector : nsISupports {

	attribute boolean enabled;
	readonly attribute short redirectCount;
	
	void addRedirect(in rdIRedirect redirect);
	void debug(in wstring msg);
	void deleteRedirectAt(in short index);
	void exportRedirects(in nsIFile file);
	rdIRedirect getRedirectAt(in short index);
	wstring getRedirectUrl(in wstring url);
	long importRedirects(in nsIFile file);
	void reload();
	void save();
	void switchItems(in short index1, in short index2);
};

